### ISSUE TITLE
test_testcase.py fails to run with py.test

### ISSUE THREAD

**Issue by 0-wiz-0** [testing-cabal/testscenarios#2]
On NetBSD-7.99.59/amd64 with python-2.7.13, pytest-3.0.6, testtools-2.2.0, test_testcase.py fails completely:
````
cd /scratch/devel/py-testscenarios/work/testscenarios-0.5.0 && py.test-2.7
============================================================================= test session starts =============================================================================
platform netbsd7 -- Python 2.7.13, pytest-3.0.6, py-1.4.30, pluggy-0.4.0
rootdir: /scratch/devel/py-testscenarios/work/testscenarios-0.5.0, inifile:
collected 26 items

doc/test_sample.py .
testscenarios/tests/test_scenarios.py ...............
testscenarios/tests/test_testcase.py FFFFFFFFFF

================================================================================== FAILURES ===================================================================================
__________________________________________________________________ TestTestWithScenarios.test_attributes_set __________________________________________________________________
NOTE: Incompatible Exception Representation, displaying natively:

_StringException: Traceback (most recent call last):
  File "/scratch/devel/py-testscenarios/work/testscenarios-0.5.0/testscenarios/tests/test_testcase.py", line 79, in test_attributes_set
    class ReferenceTest(self.Implementation):
  File "/scratch/devel/py-testscenarios/work/testscenarios-0.5.0/testscenarios/tests/test_testcase.py", line 32, in Implementation
    if isinstance(self.impl, tuple):
AttributeError: 'TestTestWithScenarios' object has no attribute 'impl'


____________________________________________________________ TestTestWithScenarios.test_countTestCases_1_scenarios ____________________________________________________________
NOTE: Incompatible Exception Representation, displaying natively:

_StringException: Traceback (most recent call last):
  File "/scratch/devel/py-testscenarios/work/testscenarios-0.5.0/testscenarios/tests/test_testcase.py", line 125, in test_countTestCases_1_scenarios
    class ReferenceTest(self.Implementation):
  File "/scratch/devel/py-testscenarios/work/testscenarios-0.5.0/testscenarios/tests/test_testcase.py", line 32, in Implementation
    if isinstance(self.impl, tuple):
AttributeError: 'TestTestWithScenarios' object has no attribute 'impl'


____________________________________________________________ TestTestWithScenarios.test_countTestCases_2_scenarios ____________________________________________________________
NOTE: Incompatible Exception Representation, displaying natively:

_StringException: Traceback (most recent call last):
  File "/scratch/devel/py-testscenarios/work/testscenarios-0.5.0/testscenarios/tests/test_testcase.py", line 133, in test_countTestCases_2_scenarios
    class ReferenceTest(self.Implementation):
  File "/scratch/devel/py-testscenarios/work/testscenarios-0.5.0/testscenarios/tests/test_testcase.py", line 32, in Implementation
    if isinstance(self.impl, tuple):
AttributeError: 'TestTestWithScenarios' object has no attribute 'impl'


__________________________________________________________ TestTestWithScenarios.test_countTestCases_empty_scenarios __________________________________________________________
NOTE: Incompatible Exception Representation, displaying natively:

_StringException: Traceback (most recent call last):
  File "/scratch/devel/py-testscenarios/work/testscenarios-0.5.0/testscenarios/tests/test_testcase.py", line 117, in test_countTestCases_empty_scenarios
    class ReferenceTest(self.Implementation):
  File "/scratch/devel/py-testscenarios/work/testscenarios-0.5.0/testscenarios/tests/test_testcase.py", line 32, in Implementation
    if isinstance(self.impl, tuple):
AttributeError: 'TestTestWithScenarios' object has no attribute 'impl'


___________________________________________________________ TestTestWithScenarios.test_countTestCases_no_scenarios ____________________________________________________________
NOTE: Incompatible Exception Representation, displaying natively:

_StringException: Traceback (most recent call last):
  File "/scratch/devel/py-testscenarios/work/testscenarios-0.5.0/testscenarios/tests/test_testcase.py", line 110, in test_countTestCases_no_scenarios
    class ReferenceTest(self.Implementation):
  File "/scratch/devel/py-testscenarios/work/testscenarios-0.5.0/testscenarios/tests/test_testcase.py", line 32, in Implementation
    if isinstance(self.impl, tuple):
AttributeError: 'TestTestWithScenarios' object has no attribute 'impl'


________________________________________________________________ TestTestWithScenarios.test_debug_2_scenarios _________________________________________________________________
NOTE: Incompatible Exception Representation, displaying natively:

_StringException: Traceback (most recent call last):
  File "/scratch/devel/py-testscenarios/work/testscenarios-0.5.0/testscenarios/tests/test_testcase.py", line 144, in test_debug_2_scenarios
    class ReferenceTest(self.Implementation):
  File "/scratch/devel/py-testscenarios/work/testscenarios-0.5.0/testscenarios/tests/test_testcase.py", line 32, in Implementation
    if isinstance(self.impl, tuple):
AttributeError: 'TestTestWithScenarios' object has no attribute 'impl'


______________________________________________________________ TestTestWithScenarios.test_no_scenarios_no_error _______________________________________________________________
NOTE: Incompatible Exception Representation, displaying natively:

_StringException: Traceback (most recent call last):
  File "/scratch/devel/py-testscenarios/work/testscenarios-0.5.0/testscenarios/tests/test_testcase.py", line 39, in test_no_scenarios_no_error
    class ReferenceTest(self.Implementation):
  File "/scratch/devel/py-testscenarios/work/testscenarios-0.5.0/testscenarios/tests/test_testcase.py", line 32, in Implementation
    if isinstance(self.impl, tuple):
AttributeError: 'TestTestWithScenarios' object has no attribute 'impl'


___________________________________________________________ TestTestWithScenarios.test_scenarios_attribute_cleared ____________________________________________________________
NOTE: Incompatible Exception Representation, displaying natively:

_StringException: Traceback (most recent call last):
  File "/scratch/devel/py-testscenarios/work/testscenarios-0.5.0/testscenarios/tests/test_testcase.py", line 93, in test_scenarios_attribute_cleared
    class ReferenceTest(self.Implementation):
  File "/scratch/devel/py-testscenarios/work/testscenarios-0.5.0/testscenarios/tests/test_testcase.py", line 32, in Implementation
    if isinstance(self.impl, tuple):
AttributeError: 'TestTestWithScenarios' object has no attribute 'impl'


____________________________________________________________ TestTestWithScenarios.test_with_one_scenario_one_run _____________________________________________________________
NOTE: Incompatible Exception Representation, displaying natively:

_StringException: Traceback (most recent call last):
  File "/scratch/devel/py-testscenarios/work/testscenarios-0.5.0/testscenarios/tests/test_testcase.py", line 49, in test_with_one_scenario_one_run
    class ReferenceTest(self.Implementation):
  File "/scratch/devel/py-testscenarios/work/testscenarios-0.5.0/testscenarios/tests/test_testcase.py", line 32, in Implementation
    if isinstance(self.impl, tuple):
AttributeError: 'TestTestWithScenarios' object has no attribute 'impl'


____________________________________________________________ TestTestWithScenarios.test_with_two_scenarios_two_run ____________________________________________________________
NOTE: Incompatible Exception Representation, displaying natively:

_StringException: Traceback (most recent call last):
  File "/scratch/devel/py-testscenarios/work/testscenarios-0.5.0/testscenarios/tests/test_testcase.py", line 63, in test_with_two_scenarios_two_run
    class ReferenceTest(self.Implementation):
  File "/scratch/devel/py-testscenarios/work/testscenarios-0.5.0/testscenarios/tests/test_testcase.py", line 32, in Implementation
    if isinstance(self.impl, tuple):
AttributeError: 'TestTestWithScenarios' object has no attribute 'impl'


==================================================================== 10 failed, 16 passed in 0.25 seconds =====================================================================
*** Error code 1

````

**Comment by jelmer** [comment]
Can you still reproduce this with master? It appears to run fine with python 2.7 on Linux.

**Comment by 0-wiz-0** [comment]
I see no improvement. NetBSD-8.99.42/amd64, python-2.7.16, testtools-2.3.0:
````
pytest-2.7
====================================================================== test session starts =======================================================================
platform netbsd8 -- Python 2.7.16, pytest-4.5.0, py-1.8.0, pluggy-0.11.0
rootdir: /disk/6/archive/foreign/testscenarios
collected 26 items                                                                                                                                               

doc/test_sample.py .                                                                                                                                       [  3%]
testscenarios/tests/test_scenarios.py ...............                                                                                                      [ 61%]
testscenarios/tests/test_testcase.py FFFFFFFFFF                                                                                                            [100%]

============================================================================ FAILURES ============================================================================
___________________________________________________________ TestTestWithScenarios.test_attributes_set ____________________________________________________________
NOTE: Incompatible Exception Representation, displaying natively:

_StringException: Traceback (most recent call last):
  File "/disk/6/archive/foreign/testscenarios/testscenarios/tests/test_testcase.py", line 79, in test_attributes_set
    class ReferenceTest(self.Implementation):
  File "/disk/6/archive/foreign/testscenarios/testscenarios/tests/test_testcase.py", line 32, in Implementation
    if isinstance(self.impl, tuple):   
AttributeError: 'TestTestWithScenarios' object has no attribute 'impl'


_____________________________________________________ TestTestWithScenarios.test_countTestCases_1_scenarios ______________________________________________________
NOTE: Incompatible Exception Representation, displaying natively:

_StringException: Traceback (most recent call last):
  File "/disk/6/archive/foreign/testscenarios/testscenarios/tests/test_testcase.py", line 125, in test_countTestCases_1_scenarios
    class ReferenceTest(self.Implementation):
  File "/disk/6/archive/foreign/testscenarios/testscenarios/tests/test_testcase.py", line 32, in Implementation
    if isinstance(self.impl, tuple):
AttributeError: 'TestTestWithScenarios' object has no attribute 'impl'


_____________________________________________________ TestTestWithScenarios.test_countTestCases_2_scenarios ______________________________________________________
NOTE: Incompatible Exception Representation, displaying natively:

_StringException: Traceback (most recent call last):
  File "/disk/6/archive/foreign/testscenarios/testscenarios/tests/test_testcase.py", line 133, in test_countTestCases_2_scenarios
    class ReferenceTest(self.Implementation):
  File "/disk/6/archive/foreign/testscenarios/testscenarios/tests/test_testcase.py", line 32, in Implementation
    if isinstance(self.impl, tuple):
AttributeError: 'TestTestWithScenarios' object has no attribute 'impl'


___________________________________________________ TestTestWithScenarios.test_countTestCases_empty_scenarios ____________________________________________________
NOTE: Incompatible Exception Representation, displaying natively:

_StringException: Traceback (most recent call last):
  File "/disk/6/archive/foreign/testscenarios/testscenarios/tests/test_testcase.py", line 117, in test_countTestCases_empty_scenarios
    class ReferenceTest(self.Implementation):
  File "/disk/6/archive/foreign/testscenarios/testscenarios/tests/test_testcase.py", line 32, in Implementation
    if isinstance(self.impl, tuple):
AttributeError: 'TestTestWithScenarios' object has no attribute 'impl'


_____________________________________________________ TestTestWithScenarios.test_countTestCases_no_scenarios _____________________________________________________
NOTE: Incompatible Exception Representation, displaying natively:

_StringException: Traceback (most recent call last):
  File "/disk/6/archive/foreign/testscenarios/testscenarios/tests/test_testcase.py", line 110, in test_countTestCases_no_scenarios
    class ReferenceTest(self.Implementation):
  File "/disk/6/archive/foreign/testscenarios/testscenarios/tests/test_testcase.py", line 32, in Implementation
    if isinstance(self.impl, tuple):
AttributeError: 'TestTestWithScenarios' object has no attribute 'impl'


__________________________________________________________ TestTestWithScenarios.test_debug_2_scenarios __________________________________________________________
NOTE: Incompatible Exception Representation, displaying natively:

_StringException: Traceback (most recent call last):
  File "/disk/6/archive/foreign/testscenarios/testscenarios/tests/test_testcase.py", line 144, in test_debug_2_scenarios
    class ReferenceTest(self.Implementation):
  File "/disk/6/archive/foreign/testscenarios/testscenarios/tests/test_testcase.py", line 32, in Implementation
    if isinstance(self.impl, tuple):
AttributeError: 'TestTestWithScenarios' object has no attribute 'impl'


________________________________________________________ TestTestWithScenarios.test_no_scenarios_no_error ________________________________________________________
NOTE: Incompatible Exception Representation, displaying natively:

_StringException: Traceback (most recent call last):
  File "/disk/6/archive/foreign/testscenarios/testscenarios/tests/test_testcase.py", line 39, in test_no_scenarios_no_error
    class ReferenceTest(self.Implementation):
  File "/disk/6/archive/foreign/testscenarios/testscenarios/tests/test_testcase.py", line 32, in Implementation
    if isinstance(self.impl, tuple):
AttributeError: 'TestTestWithScenarios' object has no attribute 'impl'


_____________________________________________________ TestTestWithScenarios.test_scenarios_attribute_cleared _____________________________________________________
NOTE: Incompatible Exception Representation, displaying natively:

_StringException: Traceback (most recent call last):
  File "/disk/6/archive/foreign/testscenarios/testscenarios/tests/test_testcase.py", line 93, in test_scenarios_attribute_cleared
    class ReferenceTest(self.Implementation):
  File "/disk/6/archive/foreign/testscenarios/testscenarios/tests/test_testcase.py", line 32, in Implementation
    if isinstance(self.impl, tuple):
AttributeError: 'TestTestWithScenarios' object has no attribute 'impl'


______________________________________________________ TestTestWithScenarios.test_with_one_scenario_one_run ______________________________________________________
NOTE: Incompatible Exception Representation, displaying natively:

_StringException: Traceback (most recent call last):
  File "/disk/6/archive/foreign/testscenarios/testscenarios/tests/test_testcase.py", line 49, in test_with_one_scenario_one_run
    class ReferenceTest(self.Implementation):
  File "/disk/6/archive/foreign/testscenarios/testscenarios/tests/test_testcase.py", line 32, in Implementation
    if isinstance(self.impl, tuple):   
AttributeError: 'TestTestWithScenarios' object has no attribute 'impl'


_____________________________________________________ TestTestWithScenarios.test_with_two_scenarios_two_run ______________________________________________________
NOTE: Incompatible Exception Representation, displaying natively:

_StringException: Traceback (most recent call last):
  File "/disk/6/archive/foreign/testscenarios/testscenarios/tests/test_testcase.py", line 63, in test_with_two_scenarios_two_run
    class ReferenceTest(self.Implementation):
  File "/disk/6/archive/foreign/testscenarios/testscenarios/tests/test_testcase.py", line 32, in Implementation
    if isinstance(self.impl, tuple):   
AttributeError: 'TestTestWithScenarios' object has no attribute 'impl'


============================================================== 10 failed, 16 passed in 1.57 seconds ==============================================================
````

**Comment by jelmer** [comment]
I don't think testscenarios is normally run with py.test. Please use "make check", "python setup.py test" or "python -m unittest testscenarios.test_suite"

**Comment by 0-wiz-0** [comment]
All three of these work, thanks.
