### ISSUE TITLE
0.5.0: pytest based test suite is failing

### ISSUE THREAD

**Issue by kloczek** [testing-cabal/testscenarios#5]
Just normal build, install and test cycle used on building package from non-root account:
- "setup.py build":
- "setup.py install --root </install/prefix>"
- "pytest with PYTHONPATH pointing to setearch and sitelib inside </install/prefix>
```console
+ /usr/bin/python3 -Bm pytest -ra
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.9, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /home/tkloczko/rpmbuild/BUILD/testscenarios-0.5.0
plugins: forked-1.3.0, shutil-1.7.0, virtualenv-1.7.0, expect-1.1.0, cov-2.11.1, httpbin-1.0.0, xdist-2.2.1, flake8-1.0.7, timeout-1.4.2, betamax-0.8.1, pyfakefs-4.4.0, freezegun-0.4.2, cases-3.4.6, case-1.5.3, isort-1.3.0, aspectlib-1.5.2, asyncio-0.15.1, toolbox-0.5, xprocess-0.17.1, flaky-3.7.0, aiohttp-0.3.0, checkdocs-2.7.0, mock-3.6.1, rerunfailures-9.1.1, requests-mock-1.9.3, hypothesis-6.13.7
collected 28 items

. . [ 3%]
doc/test_sample.py . [ 7%]
testscenarios/tests/test_scenarios.py ............... [ 62%]
testscenarios/tests/test_testcase.py FFFFFFFFFF [100%]

================================================================================= FAILURES =================================================================================
________________________________________________________________ TestTestWithScenarios.test_attributes_set _________________________________________________________________
'NoneType' object is not iterable

During handling of the above exception, another exception occurred:
NOTE: Incompatible Exception Representation, displaying natively:

testtools.testresult.real._StringException: Traceback (most recent call last):
  File "/home/tkloczko/rpmbuild/BUILD/testscenarios-0.5.0/testscenarios/tests/test_testcase.py", line 79, in test_attributes_set
    class ReferenceTest(self.Implementation):
  File "/home/tkloczko/rpmbuild/BUILD/testscenarios-0.5.0/testscenarios/tests/test_testcase.py", line 32, in Implementation
    if isinstance(self.impl, tuple):
AttributeError: 'TestTestWithScenarios' object has no attribute 'impl'
__________________________________________________________ TestTestWithScenarios.test_countTestCases_1_scenarios ___________________________________________________________
'NoneType' object is not iterable

During handling of the above exception, another exception occurred:
NOTE: Incompatible Exception Representation, displaying natively:

testtools.testresult.real._StringException: Traceback (most recent call last):
  File "/home/tkloczko/rpmbuild/BUILD/testscenarios-0.5.0/testscenarios/tests/test_testcase.py", line 125, in test_countTestCases_1_scenarios
    class ReferenceTest(self.Implementation):
  File "/home/tkloczko/rpmbuild/BUILD/testscenarios-0.5.0/testscenarios/tests/test_testcase.py", line 32, in Implementation
    if isinstance(self.impl, tuple):
AttributeError: 'TestTestWithScenarios' object has no attribute 'impl'
__________________________________________________________ TestTestWithScenarios.test_countTestCases_2_scenarios ___________________________________________________________
'NoneType' object is not iterable

During handling of the above exception, another exception occurred:
NOTE: Incompatible Exception Representation, displaying natively:

testtools.testresult.real._StringException: Traceback (most recent call last):
  File "/home/tkloczko/rpmbuild/BUILD/testscenarios-0.5.0/testscenarios/tests/test_testcase.py", line 133, in test_countTestCases_2_scenarios
    class ReferenceTest(self.Implementation):
  File "/home/tkloczko/rpmbuild/BUILD/testscenarios-0.5.0/testscenarios/tests/test_testcase.py", line 32, in Implementation
    if isinstance(self.impl, tuple):
AttributeError: 'TestTestWithScenarios' object has no attribute 'impl'
________________________________________________________ TestTestWithScenarios.test_countTestCases_empty_scenarios _________________________________________________________
'NoneType' object is not iterable

During handling of the above exception, another exception occurred:
NOTE: Incompatible Exception Representation, displaying natively:

testtools.testresult.real._StringException: Traceback (most recent call last):
  File "/home/tkloczko/rpmbuild/BUILD/testscenarios-0.5.0/testscenarios/tests/test_testcase.py", line 117, in test_countTestCases_empty_scenarios
    class ReferenceTest(self.Implementation):
  File "/home/tkloczko/rpmbuild/BUILD/testscenarios-0.5.0/testscenarios/tests/test_testcase.py", line 32, in Implementation
    if isinstance(self.impl, tuple):
AttributeError: 'TestTestWithScenarios' object has no attribute 'impl'
__________________________________________________________ TestTestWithScenarios.test_countTestCases_no_scenarios __________________________________________________________
'NoneType' object is not iterable

During handling of the above exception, another exception occurred:
NOTE: Incompatible Exception Representation, displaying natively:

testtools.testresult.real._StringException: Traceback (most recent call last):
  File "/home/tkloczko/rpmbuild/BUILD/testscenarios-0.5.0/testscenarios/tests/test_testcase.py", line 110, in test_countTestCases_no_scenarios
    class ReferenceTest(self.Implementation):
  File "/home/tkloczko/rpmbuild/BUILD/testscenarios-0.5.0/testscenarios/tests/test_testcase.py", line 32, in Implementation
    if isinstance(self.impl, tuple):
AttributeError: 'TestTestWithScenarios' object has no attribute 'impl'
_______________________________________________________________ TestTestWithScenarios.test_debug_2_scenarios _______________________________________________________________
'NoneType' object is not iterable

During handling of the above exception, another exception occurred:
NOTE: Incompatible Exception Representation, displaying natively:

testtools.testresult.real._StringException: Traceback (most recent call last):
  File "/home/tkloczko/rpmbuild/BUILD/testscenarios-0.5.0/testscenarios/tests/test_testcase.py", line 144, in test_debug_2_scenarios
    class ReferenceTest(self.Implementation):
  File "/home/tkloczko/rpmbuild/BUILD/testscenarios-0.5.0/testscenarios/tests/test_testcase.py", line 32, in Implementation
    if isinstance(self.impl, tuple):
AttributeError: 'TestTestWithScenarios' object has no attribute 'impl'
_____________________________________________________________ TestTestWithScenarios.test_no_scenarios_no_error _____________________________________________________________
'NoneType' object is not iterable

During handling of the above exception, another exception occurred:
NOTE: Incompatible Exception Representation, displaying natively:

testtools.testresult.real._StringException: Traceback (most recent call last):
  File "/home/tkloczko/rpmbuild/BUILD/testscenarios-0.5.0/testscenarios/tests/test_testcase.py", line 39, in test_no_scenarios_no_error
    class ReferenceTest(self.Implementation):
  File "/home/tkloczko/rpmbuild/BUILD/testscenarios-0.5.0/testscenarios/tests/test_testcase.py", line 32, in Implementation
    if isinstance(self.impl, tuple):
AttributeError: 'TestTestWithScenarios' object has no attribute 'impl'
__________________________________________________________ TestTestWithScenarios.test_scenarios_attribute_cleared __________________________________________________________
'NoneType' object is not iterable

During handling of the above exception, another exception occurred:
NOTE: Incompatible Exception Representation, displaying natively:

testtools.testresult.real._StringException: Traceback (most recent call last):
  File "/home/tkloczko/rpmbuild/BUILD/testscenarios-0.5.0/testscenarios/tests/test_testcase.py", line 93, in test_scenarios_attribute_cleared
    class ReferenceTest(self.Implementation):
  File "/home/tkloczko/rpmbuild/BUILD/testscenarios-0.5.0/testscenarios/tests/test_testcase.py", line 32, in Implementation
    if isinstance(self.impl, tuple):
AttributeError: 'TestTestWithScenarios' object has no attribute 'impl'
___________________________________________________________ TestTestWithScenarios.test_with_one_scenario_one_run ___________________________________________________________
'NoneType' object is not iterable

During handling of the above exception, another exception occurred:
NOTE: Incompatible Exception Representation, displaying natively:

testtools.testresult.real._StringException: Traceback (most recent call last):
  File "/home/tkloczko/rpmbuild/BUILD/testscenarios-0.5.0/testscenarios/tests/test_testcase.py", line 49, in test_with_one_scenario_one_run
    class ReferenceTest(self.Implementation):
  File "/home/tkloczko/rpmbuild/BUILD/testscenarios-0.5.0/testscenarios/tests/test_testcase.py", line 32, in Implementation
    if isinstance(self.impl, tuple):
AttributeError: 'TestTestWithScenarios' object has no attribute 'impl'
__________________________________________________________ TestTestWithScenarios.test_with_two_scenarios_two_run ___________________________________________________________
'NoneType' object is not iterable

During handling of the above exception, another exception occurred:
NOTE: Incompatible Exception Representation, displaying natively:

testtools.testresult.real._StringException: Traceback (most recent call last):
  File "/home/tkloczko/rpmbuild/BUILD/testscenarios-0.5.0/testscenarios/tests/test_testcase.py", line 63, in test_with_two_scenarios_two_run
    class ReferenceTest(self.Implementation):
  File "/home/tkloczko/rpmbuild/BUILD/testscenarios-0.5.0/testscenarios/tests/test_testcase.py", line 32, in Implementation
    if isinstance(self.impl, tuple):
AttributeError: 'TestTestWithScenarios' object has no attribute 'impl'
========================================================================= short test summary info ==========================================================================
FAILED testscenarios/tests/test_testcase.py::TestTestWithScenarios::test_attributes_set
FAILED testscenarios/tests/test_testcase.py::TestTestWithScenarios::test_countTestCases_1_scenarios
FAILED testscenarios/tests/test_testcase.py::TestTestWithScenarios::test_countTestCases_2_scenarios
FAILED testscenarios/tests/test_testcase.py::TestTestWithScenarios::test_countTestCases_empty_scenarios
FAILED testscenarios/tests/test_testcase.py::TestTestWithScenarios::test_countTestCases_no_scenarios
FAILED testscenarios/tests/test_testcase.py::TestTestWithScenarios::test_debug_2_scenarios
FAILED testscenarios/tests/test_testcase.py::TestTestWithScenarios::test_no_scenarios_no_error
FAILED testscenarios/tests/test_testcase.py::TestTestWithScenarios::test_scenarios_attribute_cleared
FAILED testscenarios/tests/test_testcase.py::TestTestWithScenarios::test_with_one_scenario_one_run
FAILED testscenarios/tests/test_testcase.py::TestTestWithScenarios::test_with_two_scenarios_two_run
====================================================================== 10 failed, 17 passed in 6.96s =======================================================================
``

**Comment by jelmer** [comment]
testscenarios doesn't use pytest, but either testtools or the python-standard unittest. See discussions in similar packages.
